### PR TITLE
changing text from Configuration to Team

### PR DESCRIPTION
**Pull request by mariadeck**
issue #345

### CODE REVIEW

**Comment by ewingrj** [comment]
Deploy preview for *geome-develop* ready!

Built with commit 2a042a10c392f3f6f014caed8eb935588eba6d5b

https://deploy-preview-365--geome-develop.netlify.com

**Comment by jdeck88** [comment]
For tooltip text: "Teams consist of projects sharing a common set of rules, attributes, and controlled vocabulary terms."

**Comment by ewingrj** [comment]
can you fix the conflicts, then this is good to merge

**Comment by mariadeck** [comment]
ready to go

**Pull request merged**
