### PR TITLE
Team overview

### PR DESCRIPTION
**Pull request by albarqmaria**
Team overview page developed. To be added after API update: 
-Full team details including DOI, Website and Documentation
-Logo image 
addresses issue #423

### CODE REVIEW

**Comment by ewingrj** [comment]
Deploy preview for *geome-develop* ready!

Built with commit 25a6c67a4640391a7a73fc19fdf37c24275e96ba

https://deploy-preview-435--geome-develop.netlify.com

**Comment by jdeck88** [comment]
ok, some changes based on the most recent PR. we need to make getting to the "Team Overview" more intuitive.
1) On the Project listing after you click on Workbench, there are "Team Badges".  Click
the team badge and jump to the Team Overview for that Team.
2) On the Project Overview there is a spot where it lists what team the project is part of.  Click on the the link for the team to jump to the Team Overview.  Better yet, use the same badge styling for teams that are on the project listing page.
3) Finally, i think we need a "View Teams" Link at the top of the left menu to display teams and then a user can click on each team in that list to jump to the "Team Overview" (and from there that lists relevant projects)

**Comment by albarqmaria** [comment]
1 : Good idea, i will turn those badges into links
2: ok, i can use the same badge styling & create link for team under Project Overview
3: I will be making a "View Teams" page, based on this mockup, just havent finished it yet 
75843383-12f20900-5de4-11ea-91f6-c1fd4d74b7b5

**Comment by jdeck88** [comment]
Great progress.   
one small thing: only show the open to collaborate logo but not the checkbox or text.

as soon as you create the "View Teams" option on the left,  i'll merge.

**Comment by albarqmaria** [comment]
Note: the recent commit is an outline for the teams list view. Correct data for the table has not been added.

**Comment by jdeck88** [comment]
I see there is a "View Teams" link there now... but when i click on it, i see a bunch of JSON at the top, and the link does not bring me to a specific team view.  still in progress?

**Comment by albarqmaria** [comment]
Yes, the data has not been added. I made the commit so I could check out a different branch, should have stashed it.

**Comment by jdeck88** [comment]
The data is fine as is... just use you what we have... we can add the rest later. i want to have the team view ready sooner rather than later.

John

**Comment by jdeck88** [comment]
Looking good... a few small items to fix:

1) the spacing between the modules on the teams view is too large... i just want a few pixels spacing there... i've attached what it looks like on my browser here:
image

2) The titles on long projects are getting truncated... can you wrap them? or, make the spot where the title goes larger.. attached is what it looks like on my browser:
image

3) Finally, remove the "Open to collaborate" logo and option box from the team page.  that is not quite ready for adoption (i want to wait until we enable team metadata)

**Comment by albarqmaria** [comment]
> Looking good... a few small items to fix:
> 
> 1a) the spacing between the modules on the teams view is too large... i just want a few pixels spacing there... i've attached what it looks like on my browser here.
> image
> OK, I've added 5px to the margin and removed the space-between class
> 1b) Also, about the buttons here... i think we should make the buttons here a different color than the "team" buttons that are blue. my expectation is that i can click on them and have them do something special, but really they do not. Can you make the button color something less attractive so people (like me) are not inclined to click on them?
> I've changed the bootstrap "label-info" class to "label-default," which is grey. 
> 1. The titles on long projects are getting truncated... can you wrap them? or, make the spot where the title goes larger.. attached is what it looks like on my browser:
>    image

Ok, I've changed the size of the team title column in both the team overview and teams list views to take up more space, which gives the titles enough space so that they dont truncate on medium, large and xl devices 

> 2. Finally, remove the "Open to collaborate" logo and option box from the team page.  that is not quite ready for adoption (i want to wait until we enable team metadata)

removed. I left the code in comments in case we want that code when the team metadata is enabled.

**Pull request merged**
