### PR TITLE
Team query

### PR DESCRIPTION
**Pull request by albarqmaria**
addresses issue #439 

This only includes a special team query view for the Amphibian Disease team, Biocode team query has not been implemented yet. 
Please comment with any needed changes...

### CODE REVIEW

**Comment by albarqmaria** [comment]
Not sure whats going on with Netlify... but you could pull it locally, here's the url for Amphibian Disease Team Query:

http://localhost:3000/query?team=45

**Comment by ewingrj** [comment]
Deploy preview for *geome-develop* ready!

Built with commit 0cc01aba10e7a9436076a734f6fbd861522633ed

https://deploy-preview-443--geome-develop.netlify.app

**Comment by albarqmaria** [comment]
https://deploy-preview-443--geome-develop.netlify.app/query?team=45

**Comment by jdeck88** [comment]
Can you look into the following javascript error coming up on my console when loading the query page:
image

**Pull request merged**
